#
# Copyright (c) 2015. Sunisco and/or its affiliates.
#

# SPRING CONFIG (ConfigFileApplicationListener)
#spring.config.name= # config file name (default to 'application')
#spring.config.location=classpath*:/conf/context/**/*-context.xml

# Server settings (ServerProperties)
server:
  port: 1000
  address: 0.0.0.0
  sessionTimeout: 30
#  contextPath: /

# Tomcat specifics
  tomcat.accessLogEnabled: false
#server.tomcat.protocolHeader=x-forwarded-proto
#server.tomcat.remoteIpHeader=x-forwarded-for
  tomcat.backgroundProcessorDelay: 30
  tomcat.uri-encoding: UTF-8

#spring.resources.add-mappings=true

spring:
  http.encoding.enabled: true
  datasource:
    driverClassName: org.h2.Driver
    datasource.url: jdbc:h2:~/demo
    datasource.username: demo
    datasource.password:

#"none", "validate", "update", "create", "create-drop"
  jpa.hibernate.ddl-auto: update
  jpa.database: H2
  jpa.showsql: true

  jackson.date-format: yyyy-MM-dd HH:mm:ss
  jackson.joda-date-time-format: yyyy-MM-dd HH:mm:ss
  jackson.serialization.INDENT_OUTPUT: true

#security.enableCsrf=true
#security.basic.enabled=false

#management.context-path=/manage
#management.port=9091
#management.security.role=SUPERUSER
#security.user.name=admin
#security.user.password=secret



