spring:
  application:
    name: eureka-server
server:
  port: 8761

eureka:
  environment: ${EUREKA_ENV:test}
  instance:
    hostname: ${HOSTNAME}
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

